---

- name: deactivate default configuration
  notify: reload nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx customize directory
  file:
    path: /etc/nginx/customize
    state: directory

- name: send customization files
  notify: reload nginx
  copy:
    dest: "/etc/nginx/customize/{{ item | basename }}"
    src: "{{ item }}"
  with_fileglob: files/nginx/customize/*.conf
